import { describe, expect, it } from "vitest"

import {
  ADMISSION_STATE,
  CREATE_JOURNAL_STATE,
  CREATE_REPLAY_STATE,
  EMERGENCY_RECOVERY_STATE,
  LEGACY_BOOTSTRAP_STATE,
  MANAGER_MODE,
  SESSION_STATE,
  WORKER_STATE,
} from "../src/control-plane-vocabulary.js"
import {
  canAdmissionTransition,
  canCreateJournalTransition,
  canCreateReplayTransition,
  canEmergencyRecoveryTransition,
  canLegacyBootstrapTransition,
  canManagerModeTransition,
  canSessionTransition,
  canWorkerTransition,
} from "../src/control-plane-transitions.js"

type Vocabulary = Readonly<Record<string, string>>
type Edge = readonly [string, string]

const MACHINES = [
  [WORKER_STATE, canWorkerTransition, [
    [WORKER_STATE.DISCOVERED, WORKER_STATE.REACHABLE], [WORKER_STATE.DISCOVERED, WORKER_STATE.UNREACHABLE], [WORKER_STATE.DISCOVERED, WORKER_STATE.QUARANTINED], [WORKER_STATE.DISCOVERED, WORKER_STATE.DRAINING],
    [WORKER_STATE.REACHABLE, WORKER_STATE.IDLE], [WORKER_STATE.REACHABLE, WORKER_STATE.UNREACHABLE], [WORKER_STATE.REACHABLE, WORKER_STATE.QUARANTINED], [WORKER_STATE.REACHABLE, WORKER_STATE.DRAINING],
    [WORKER_STATE.IDLE, WORKER_STATE.RESERVED], [WORKER_STATE.IDLE, WORKER_STATE.UNREACHABLE], [WORKER_STATE.IDLE, WORKER_STATE.QUARANTINED], [WORKER_STATE.IDLE, WORKER_STATE.DRAINING],
    [WORKER_STATE.RESERVED, WORKER_STATE.STARTING], [WORKER_STATE.RESERVED, WORKER_STATE.IDLE], [WORKER_STATE.RESERVED, WORKER_STATE.UNREACHABLE], [WORKER_STATE.RESERVED, WORKER_STATE.QUARANTINED], [WORKER_STATE.RESERVED, WORKER_STATE.DRAINING],
    [WORKER_STATE.STARTING, WORKER_STATE.LIVE], [WORKER_STATE.STARTING, WORKER_STATE.IDLE], [WORKER_STATE.STARTING, WORKER_STATE.UNREACHABLE], [WORKER_STATE.STARTING, WORKER_STATE.QUARANTINED], [WORKER_STATE.STARTING, WORKER_STATE.DRAINING],
    [WORKER_STATE.LIVE, WORKER_STATE.RELEASING], [WORKER_STATE.LIVE, WORKER_STATE.UNREACHABLE], [WORKER_STATE.LIVE, WORKER_STATE.QUARANTINED], [WORKER_STATE.LIVE, WORKER_STATE.DRAINING],
    [WORKER_STATE.RELEASING, WORKER_STATE.IDLE], [WORKER_STATE.RELEASING, WORKER_STATE.UNREACHABLE], [WORKER_STATE.RELEASING, WORKER_STATE.QUARANTINED], [WORKER_STATE.RELEASING, WORKER_STATE.DRAINING],
    [WORKER_STATE.UNREACHABLE, WORKER_STATE.REACHABLE], [WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED], [WORKER_STATE.UNREACHABLE, WORKER_STATE.DRAINING],
    [WORKER_STATE.QUARANTINED, WORKER_STATE.DISCOVERED], [WORKER_STATE.QUARANTINED, WORKER_STATE.IDLE], [WORKER_STATE.QUARANTINED, WORKER_STATE.LIVE], [WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
    [WORKER_STATE.DRAINING, WORKER_STATE.IDLE], [WORKER_STATE.DRAINING, WORKER_STATE.UNREACHABLE], [WORKER_STATE.DRAINING, WORKER_STATE.QUARANTINED],
  ]],
  [SESSION_STATE, canSessionTransition, [
    [SESSION_STATE.QUEUED, SESSION_STATE.STARTING], [SESSION_STATE.QUEUED, SESSION_STATE.FAILED],
    [SESSION_STATE.STARTING, SESSION_STATE.LIVE], [SESSION_STATE.STARTING, SESSION_STATE.FAILED], [SESSION_STATE.STARTING, SESSION_STATE.LOST],
    [SESSION_STATE.LIVE, SESSION_STATE.RELEASING], [SESSION_STATE.LIVE, SESSION_STATE.LOST],
    [SESSION_STATE.RELEASING, SESSION_STATE.RELEASED], [SESSION_STATE.RELEASING, SESSION_STATE.LOST],
  ]],
  [ADMISSION_STATE, canAdmissionTransition, [
    [ADMISSION_STATE.QUEUED, ADMISSION_STATE.RESERVED], [ADMISSION_STATE.QUEUED, ADMISSION_STATE.CANCELLED], [ADMISSION_STATE.QUEUED, ADMISSION_STATE.EXPIRED], [ADMISSION_STATE.QUEUED, ADMISSION_STATE.FAILED],
    [ADMISSION_STATE.RESERVED, ADMISSION_STATE.STARTING], [ADMISSION_STATE.RESERVED, ADMISSION_STATE.CANCELLED], [ADMISSION_STATE.RESERVED, ADMISSION_STATE.EXPIRED], [ADMISSION_STATE.RESERVED, ADMISSION_STATE.FAILED],
    [ADMISSION_STATE.STARTING, ADMISSION_STATE.ADMITTED], [ADMISSION_STATE.STARTING, ADMISSION_STATE.CANCELLED], [ADMISSION_STATE.STARTING, ADMISSION_STATE.EXPIRED], [ADMISSION_STATE.STARTING, ADMISSION_STATE.FAILED],
  ]],
  [CREATE_JOURNAL_STATE, canCreateJournalTransition, [
    [CREATE_JOURNAL_STATE.ACCEPTED, CREATE_JOURNAL_STATE.UPSTREAM_PENDING], [CREATE_JOURNAL_STATE.ACCEPTED, CREATE_JOURNAL_STATE.UNCERTAIN], [CREATE_JOURNAL_STATE.ACCEPTED, CREATE_JOURNAL_STATE.FAILED_TERMINAL],
    [CREATE_JOURNAL_STATE.UPSTREAM_PENDING, CREATE_JOURNAL_STATE.LIVE], [CREATE_JOURNAL_STATE.UPSTREAM_PENDING, CREATE_JOURNAL_STATE.UNCERTAIN], [CREATE_JOURNAL_STATE.UPSTREAM_PENDING, CREATE_JOURNAL_STATE.FAILED_TERMINAL],
    [CREATE_JOURNAL_STATE.LIVE, CREATE_JOURNAL_STATE.RELEASED_TERMINAL], [CREATE_JOURNAL_STATE.LIVE, CREATE_JOURNAL_STATE.UNCERTAIN],
    [CREATE_JOURNAL_STATE.UNCERTAIN, CREATE_JOURNAL_STATE.LIVE], [CREATE_JOURNAL_STATE.UNCERTAIN, CREATE_JOURNAL_STATE.RELEASED_TERMINAL], [CREATE_JOURNAL_STATE.UNCERTAIN, CREATE_JOURNAL_STATE.FAILED_TERMINAL],
  ]],
  [CREATE_REPLAY_STATE, canCreateReplayTransition, [
    [CREATE_REPLAY_STATE.QUEUED, CREATE_REPLAY_STATE.RESERVED], [CREATE_REPLAY_STATE.QUEUED, CREATE_REPLAY_STATE.CANCELLED_TERMINAL], [CREATE_REPLAY_STATE.QUEUED, CREATE_REPLAY_STATE.EXPIRED_TERMINAL], [CREATE_REPLAY_STATE.QUEUED, CREATE_REPLAY_STATE.FAILED_TERMINAL],
    [CREATE_REPLAY_STATE.RESERVED, CREATE_REPLAY_STATE.STARTING], [CREATE_REPLAY_STATE.RESERVED, CREATE_REPLAY_STATE.CANCELLED_TERMINAL], [CREATE_REPLAY_STATE.RESERVED, CREATE_REPLAY_STATE.EXPIRED_TERMINAL], [CREATE_REPLAY_STATE.RESERVED, CREATE_REPLAY_STATE.FAILED_TERMINAL],
    [CREATE_REPLAY_STATE.STARTING, CREATE_REPLAY_STATE.WORKER_PENDING], [CREATE_REPLAY_STATE.STARTING, CREATE_REPLAY_STATE.CANCELLED_TERMINAL], [CREATE_REPLAY_STATE.STARTING, CREATE_REPLAY_STATE.EXPIRED_TERMINAL], [CREATE_REPLAY_STATE.STARTING, CREATE_REPLAY_STATE.FAILED_TERMINAL],
    [CREATE_REPLAY_STATE.WORKER_PENDING, CREATE_REPLAY_STATE.LIVE], [CREATE_REPLAY_STATE.WORKER_PENDING, CREATE_REPLAY_STATE.CANCELLED_TERMINAL], [CREATE_REPLAY_STATE.WORKER_PENDING, CREATE_REPLAY_STATE.EXPIRED_TERMINAL], [CREATE_REPLAY_STATE.WORKER_PENDING, CREATE_REPLAY_STATE.FAILED_TERMINAL],
    [CREATE_REPLAY_STATE.LIVE, CREATE_REPLAY_STATE.RELEASED_TERMINAL],
  ]],
  [MANAGER_MODE, canManagerModeTransition, [[MANAGER_MODE.SERVING, MANAGER_MODE.DRAINING], [MANAGER_MODE.DRAINING, MANAGER_MODE.SERVING]]],
  [EMERGENCY_RECOVERY_STATE, canEmergencyRecoveryTransition, [
    [EMERGENCY_RECOVERY_STATE.MAINTENANCE, EMERGENCY_RECOVERY_STATE.RECOVER_MANAGER],
    [EMERGENCY_RECOVERY_STATE.RECOVER_MANAGER, EMERGENCY_RECOVERY_STATE.NATURAL_QUIESCENCE],
    [EMERGENCY_RECOVERY_STATE.NATURAL_QUIESCENCE, EMERGENCY_RECOVERY_STATE.DESTRUCTIVE_STOPPED],
    [EMERGENCY_RECOVERY_STATE.DESTRUCTIVE_STOPPED, EMERGENCY_RECOVERY_STATE.SAFE_FOR_LEGACY],
  ]],
  [LEGACY_BOOTSTRAP_STATE, canLegacyBootstrapTransition, [
    [LEGACY_BOOTSTRAP_STATE.SERVING, LEGACY_BOOTSTRAP_STATE.EDGE_FENCED],
    [LEGACY_BOOTSTRAP_STATE.EDGE_FENCED, LEGACY_BOOTSTRAP_STATE.QUIESCENT],
    [LEGACY_BOOTSTRAP_STATE.QUIESCENT, LEGACY_BOOTSTRAP_STATE.STOPPED],
  ]],
] as const satisfies readonly [Vocabulary, (from: never, to: never) => boolean, readonly Edge[]][]

describe("independent control-plane transition oracle", () => {
  it.each(MACHINES)("covers every legal and illegal edge for machine %#", (vocabulary, predicate, legalEdges) => {
    // Given: an independently declared legal-edge set and the closed state cross-product.
    const legal = new Set(legalEdges.map(([from, to]) => `${from}->${to}`))
    const members = Object.values(vocabulary)
    const pairs = members.flatMap((from) => members.map((to) => [from, to] as const))
    // When: every public transition predicate cell is evaluated.
    const observed = pairs.map(([from, to]) => predicate(from, to))
    // Then: each legal edge is true and every undeclared edge is false.
    expect(observed).toEqual(pairs.map(([from, to]) => legal.has(`${from}->${to}`)))
  })

  it("keeps RELEASED terminal", () => {
    // Given: a released session and a proposed return to live service.
    // When: the independent public predicate evaluates the mutation target.
    const allowed = canSessionTransition(SESSION_STATE.RELEASED, SESSION_STATE.LIVE)
    // Then: terminal state resurrection is forbidden.
    expect(allowed).toBe(false)
  })
})
