import {
  MANAGED_ERROR_CODE,
  type ManagedErrorCode,
} from "@happycastle/steel-managed-shared";

export const READ_ERRORS = [
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
] as const satisfies readonly ManagedErrorCode[];

export const LIST_ERRORS = [
  MANAGED_ERROR_CODE.INVALID_ARGUMENT,
  MANAGED_ERROR_CODE.INVALID_CURSOR,
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.LIST_CURSOR_RESTARTED,
  MANAGED_ERROR_CODE.LIST_CURSOR_EXPIRED,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
  MANAGED_ERROR_CODE.MANAGED_SNAPSHOT_CAPACITY,
] as const satisfies readonly ManagedErrorCode[];

export const OPERATOR_LIST_ERRORS = [
  ...LIST_ERRORS,
  MANAGED_ERROR_CODE.ACCESS_FORBIDDEN,
] as const satisfies readonly ManagedErrorCode[];

export const EVENT_ERRORS = [
  MANAGED_ERROR_CODE.INVALID_ARGUMENT,
  MANAGED_ERROR_CODE.INVALID_CURSOR,
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.ACCESS_FORBIDDEN,
  MANAGED_ERROR_CODE.EVENT_CURSOR_RESTARTED,
  MANAGED_ERROR_CODE.EVENT_CURSOR_EXPIRED,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
] as const satisfies readonly ManagedErrorCode[];

export const SESSION_DETAIL_ERRORS = [
  MANAGED_ERROR_CODE.INVALID_ARGUMENT,
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.SESSION_NOT_FOUND,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
] as const satisfies readonly ManagedErrorCode[];

export const ADMISSION_DETAIL_ERRORS = [
  MANAGED_ERROR_CODE.INVALID_ARGUMENT,
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.ADMISSION_NOT_FOUND,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
] as const satisfies readonly ManagedErrorCode[];

export const CREATE_ERRORS = [
  MANAGED_ERROR_CODE.INVALID_ARGUMENT,
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.CREATE_TOKEN_CONFLICT,
  MANAGED_ERROR_CODE.ADMISSION_TIMEOUT,
  MANAGED_ERROR_CODE.QUEUE_FULL,
  MANAGED_ERROR_CODE.RATE_LIMITED,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
  MANAGED_ERROR_CODE.NO_REACHABLE_WORKER,
  MANAGED_ERROR_CODE.MANAGER_DRAINING,
  MANAGED_ERROR_CODE.MANAGED_LIMITER_CAPACITY,
  MANAGED_ERROR_CODE.MANAGED_TICKET_CAPACITY,
  MANAGED_ERROR_CODE.MANAGED_IDEMPOTENCY_CAPACITY,
  MANAGED_ERROR_CODE.UPSTREAM_TIMEOUT,
] as const satisfies readonly ManagedErrorCode[];

export const SESSION_MUTATION_ERRORS = [
  ...SESSION_DETAIL_ERRORS,
  MANAGED_ERROR_CODE.SESSION_STATE_CONFLICT,
  MANAGED_ERROR_CODE.UPSTREAM_TIMEOUT,
] as const satisfies readonly ManagedErrorCode[];

export const ADMISSION_MUTATION_ERRORS = [
  ...ADMISSION_DETAIL_ERRORS,
  MANAGED_ERROR_CODE.SESSION_STATE_CONFLICT,
  MANAGED_ERROR_CODE.UPSTREAM_TIMEOUT,
] as const satisfies readonly ManagedErrorCode[];

export const POOL_MUTATION_ERRORS = [
  MANAGED_ERROR_CODE.INVALID_ARGUMENT,
  MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED,
  MANAGED_ERROR_CODE.ACCESS_FORBIDDEN,
  MANAGED_ERROR_CODE.SESSION_STATE_CONFLICT,
  MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE,
  MANAGED_ERROR_CODE.MANAGED_IDEMPOTENCY_CAPACITY,
] as const satisfies readonly ManagedErrorCode[];
