/* This file is generated by generate-artifacts-cli.ts. Do not edit. */
import {
  AdmissionIdSchema,
  AdmissionListQuerySchema,
  AdmissionListSchema,
  AdmissionSchema,
  EventQuerySchema,
  EventListSchema,
  MANAGER_MODE,
  MANAGED_ERROR_CATALOG,
  ManagedAdmissionCreateRequestSchema,
  ManagedErrorEnvelopeSchema,
  PoolDrainRequestSchema,
  PoolResumeRequestSchema,
  poolSchemaForConfig,
  SessionIdSchema,
  SessionListQuerySchema,
  SessionListSchema,
  SessionSchema,
  VersionSchema,
  WorkerListQuerySchema,
  WorkerListSchema,
  type AdmissionId,
  type AdmissionState,
  type ControlPlaneConfig,
  type SessionId,
  type SessionState,
  type WorkerState,
} from "@happycastle/steel-managed-shared/browser"
import { z } from "zod"
export const MANAGED_CLIENT_ROUTE_INVENTORY = Object.freeze([{"method":"GET","path":"/v1/managed/pool","successStatus":200},{"method":"GET","path":"/v1/managed/workers","successStatus":200},{"method":"GET","path":"/v1/managed/sessions","successStatus":200},{"method":"GET","path":"/v1/managed/sessions/:id","successStatus":200},{"method":"GET","path":"/v1/managed/queue","successStatus":200},{"method":"GET","path":"/v1/managed/events","successStatus":200},{"method":"GET","path":"/v1/managed/admissions/:id","successStatus":200},{"method":"GET","path":"/v1/managed/version","successStatus":200},{"method":"POST","path":"/v1/managed/admissions","successStatus":202},{"method":"POST","path":"/v1/managed/admissions/:id/cancel","successStatus":200},{"method":"POST","path":"/v1/managed/sessions/:id/release","successStatus":200},{"method":"POST","path":"/v1/managed/pool/drain","successStatus":200},{"method":"POST","path":"/v1/managed/pool/resume","successStatus":200}])
export type ManagedAdmission = z.output<typeof AdmissionSchema>
export type ManagedAdmissionCreateInput = z.input<typeof ManagedAdmissionCreateRequestSchema>
export type ManagedAdmissionList = z.output<typeof AdmissionListSchema>
export type ManagedEventList = z.output<typeof EventListSchema>
export type ManagedPool = z.output<ReturnType<typeof poolSchemaForConfig>>
export type ManagedPoolDrainInput = z.input<typeof PoolDrainRequestSchema>
export type ManagedPoolResumeInput = z.input<typeof PoolResumeRequestSchema>
export type ManagedSession = z.output<typeof SessionSchema>
export type ManagedSessionList = z.output<typeof SessionListSchema>
export type ManagedVersion = z.output<typeof VersionSchema>
export type ManagedWorkerList = z.output<typeof WorkerListSchema>
export type ManagedErrorEnvelope = z.output<typeof ManagedErrorEnvelopeSchema>
export type ManagedListQuery<State extends string> = Readonly<{
  cursor?: string
  pageSize?: number
  state?: readonly State[]
}>
export type ManagedEventQuery = Readonly<{
  cursor?: string
  pageSize?: number
  snapshotCursor?: string
}>
export type ManagedFetchRequest = Readonly<{
  body?: string
  headers: Readonly<Record<string, string>>
  method: "GET" | "POST"
}>
export type ManagedFetchResponse = Readonly<{
  json: () => Promise<unknown>
  ok: boolean
  status: number
}>
export type ManagedFetch = (url: string, request: ManagedFetchRequest) => Promise<ManagedFetchResponse>
export type ManagedOperationsClientOptions = Readonly<{
  baseUrl: string
  config: ControlPlaneConfig
  fetch: ManagedFetch
  headers?: Readonly<Record<string, string>>
}>
export class ManagedApiError extends Error {
  public override readonly name = "ManagedApiError"

  public constructor(
    public readonly status: number,
    public readonly envelope: ManagedErrorEnvelope,
  ) {
    super(envelope.error.message)
  }
}
export class ManagedApiProtocolError extends Error {
  public override readonly name = "ManagedApiProtocolError"
}
function appendCommonQuery(
  parameters: URLSearchParams,
  query: Readonly<{ cursor?: string; pageSize?: number }>,
): void {
  if (query.cursor !== undefined) parameters.set("cursor", query.cursor)
  if (query.pageSize !== undefined) parameters.set("pageSize", String(query.pageSize))
}

function listPath<State extends string>(path: string, query: ManagedListQuery<State> = {}): string {
  const parameters = new URLSearchParams()
  appendCommonQuery(parameters, query)
  for (const state of query.state ?? []) parameters.append("state", state)
  const encoded = parameters.toString()
  return encoded.length === 0 ? path : path + "?" + encoded
}

function eventPath(query: ManagedEventQuery = {}): string {
  const parameters = new URLSearchParams()
  appendCommonQuery(parameters, query)
  if (query.snapshotCursor !== undefined) parameters.set("snapshotCursor", query.snapshotCursor)
  const encoded = parameters.toString()
  return encoded.length === 0 ? "/v1/managed/events" : "/v1/managed/events?" + encoded
}

function bindSessionIdentity(requestedId: SessionId, session: ManagedSession): ManagedSession {
  if (session.sessionId !== requestedId) {
    throw new ManagedApiProtocolError("Managed API returned a session for a different requested ID")
  }
  return session
}

function bindAdmissionIdentity(requestedId: AdmissionId, admission: ManagedAdmission): ManagedAdmission {
  if (admission.admissionId !== requestedId) {
    throw new ManagedApiProtocolError("Managed API returned an admission for a different requested ID")
  }
  return admission
}

export class ManagedOperationsClient {
  private readonly baseUrl: string
  private readonly poolSchema: ReturnType<typeof poolSchemaForConfig>

  public constructor(private readonly options: ManagedOperationsClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/u, "")
    this.poolSchema = poolSchemaForConfig(options.config)
  }

  public getPool(): Promise<ManagedPool> {
    return this.request(this.poolSchema, 200, "GET", "/v1/managed/pool")
  }

  public listWorkers(query: ManagedListQuery<WorkerState> = {}): Promise<ManagedWorkerList> {
    WorkerListQuerySchema.parse(query)
    return this.request(WorkerListSchema, 200, "GET", listPath("/v1/managed/workers", query))
  }

  public listSessions(query: ManagedListQuery<SessionState> = {}): Promise<ManagedSessionList> {
    SessionListQuerySchema.parse(query)
    return this.request(SessionListSchema, 200, "GET", listPath("/v1/managed/sessions", query))
  }

  public async getSession(sessionId: SessionId): Promise<ManagedSession> {
    const requestedId = SessionIdSchema.parse(sessionId)
    const session = await this.request(SessionSchema, 200, "GET", "/v1/managed/sessions/" + encodeURIComponent(requestedId))
    return bindSessionIdentity(requestedId, session)
  }

  public listQueue(query: ManagedListQuery<AdmissionState> = {}): Promise<ManagedAdmissionList> {
    AdmissionListQuerySchema.parse(query)
    return this.request(AdmissionListSchema, 200, "GET", listPath("/v1/managed/queue", query))
  }

  public listEvents(query: ManagedEventQuery = {}): Promise<ManagedEventList> {
    EventQuerySchema.parse(query)
    return this.request(EventListSchema, 200, "GET", eventPath(query))
  }

  public async getAdmission(admissionId: AdmissionId): Promise<ManagedAdmission> {
    const requestedId = AdmissionIdSchema.parse(admissionId)
    const admission = await this.request(AdmissionSchema, 200, "GET", "/v1/managed/admissions/" + encodeURIComponent(requestedId))
    return bindAdmissionIdentity(requestedId, admission)
  }

  public getVersion(): Promise<ManagedVersion> {
    return this.request(VersionSchema, 200, "GET", "/v1/managed/version")
  }

  public createAdmission(input: ManagedAdmissionCreateInput): Promise<ManagedAdmission> {
    return this.request(AdmissionSchema, 202, "POST", "/v1/managed/admissions", ManagedAdmissionCreateRequestSchema.parse(input))
  }

  public async cancelAdmission(admissionId: AdmissionId): Promise<ManagedAdmission> {
    const requestedId = AdmissionIdSchema.parse(admissionId)
    const admission = await this.request(AdmissionSchema, 200, "POST", "/v1/managed/admissions/" + encodeURIComponent(requestedId) + "/cancel", {})
    return bindAdmissionIdentity(requestedId, admission)
  }

  public async releaseSession(sessionId: SessionId): Promise<ManagedSession> {
    const requestedId = SessionIdSchema.parse(sessionId)
    const session = await this.request(SessionSchema, 200, "POST", "/v1/managed/sessions/" + encodeURIComponent(requestedId) + "/release", {})
    return bindSessionIdentity(requestedId, session)
  }

  public async drainPool(input: ManagedPoolDrainInput): Promise<ManagedPool> {
    const request = PoolDrainRequestSchema.parse(input)
    const pool = await this.request(this.poolSchema, 200, "POST", "/v1/managed/pool/drain", request)
    if (pool.managerInstanceId !== request.expectedManagerInstanceId || pool.mode !== MANAGER_MODE.DRAINING) {
      throw new ManagedApiProtocolError("Managed API returned an invalid drain result")
    }
    return pool
  }

  public async resumePool(input: ManagedPoolResumeInput): Promise<ManagedPool> {
    const request = PoolResumeRequestSchema.parse(input)
    const pool = await this.request(this.poolSchema, 200, "POST", "/v1/managed/pool/resume", request)
    if (pool.managerInstanceId !== request.expectedManagerInstanceId || pool.mode !== MANAGER_MODE.SERVING) {
      throw new ManagedApiProtocolError("Managed API returned an invalid resume result")
    }
    return pool
  }

  private async request<Output, Definition extends z.ZodTypeDef, Input>(
    schema: z.ZodType<Output, Definition, Input>,
    expectedStatus: 200 | 202,
    method: "GET" | "POST",
    path: string,
    body?: unknown,
  ): Promise<Output> {
    const response = await this.options.fetch(this.baseUrl + path, {
      method,
      headers: {
        ...this.options.headers,
        accept: "application/json",
        ...(body === undefined ? {} : { "content-type": "application/json" }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    })
    const payload = await response.json()
    if (!response.ok) {
      const parsedError = ManagedErrorEnvelopeSchema.safeParse(payload)
      if (parsedError.success && MANAGED_ERROR_CATALOG[parsedError.data.error.code].status === response.status) {
        throw new ManagedApiError(response.status, parsedError.data)
      }
      throw new ManagedApiProtocolError("Managed API returned an invalid error response")
    }
    if (response.status !== expectedStatus) {
      throw new ManagedApiProtocolError("Managed API returned an unexpected success status")
    }
    const parsed = schema.safeParse(payload)
    if (!parsed.success) throw new ManagedApiProtocolError("Managed API returned an invalid success response")
    return parsed.data
  }
}
