import {
  ADMISSION_STATE,
  CREATE_JOURNAL_STATE,
  CREATE_REPLAY_STATE,
  EMERGENCY_RECOVERY_STATE,
  LEGACY_BOOTSTRAP_STATE,
  MANAGER_MODE,
  SESSION_STATE,
  WORKER_STATE,
  type AdmissionState,
  type CreateJournalState,
  type CreateReplayState,
  type EmergencyRecoveryState,
  type LegacyBootstrapState,
  type ManagerMode,
  type SessionState,
  type WorkerState,
} from "./control-plane-vocabulary.js"

type TransitionTable<State extends string> = Readonly<Record<State, readonly State[]>>

export const WORKER_TRANSITIONS = {
  [WORKER_STATE.DISCOVERED]: [WORKER_STATE.REACHABLE, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.REACHABLE]: [WORKER_STATE.IDLE, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.IDLE]: [WORKER_STATE.RESERVED, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.RESERVED]: [WORKER_STATE.STARTING, WORKER_STATE.IDLE, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.STARTING]: [WORKER_STATE.LIVE, WORKER_STATE.IDLE, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.LIVE]: [WORKER_STATE.RELEASING, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.RELEASING]: [WORKER_STATE.IDLE, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.UNREACHABLE]: [WORKER_STATE.REACHABLE, WORKER_STATE.QUARANTINED, WORKER_STATE.DRAINING],
  [WORKER_STATE.QUARANTINED]: [WORKER_STATE.DISCOVERED, WORKER_STATE.IDLE, WORKER_STATE.LIVE, WORKER_STATE.DRAINING],
  [WORKER_STATE.DRAINING]: [WORKER_STATE.IDLE, WORKER_STATE.UNREACHABLE, WORKER_STATE.QUARANTINED],
} as const satisfies TransitionTable<WorkerState>

export const SESSION_TRANSITIONS = {
  [SESSION_STATE.QUEUED]: [SESSION_STATE.STARTING, SESSION_STATE.FAILED],
  [SESSION_STATE.STARTING]: [SESSION_STATE.LIVE, SESSION_STATE.FAILED, SESSION_STATE.LOST],
  [SESSION_STATE.LIVE]: [SESSION_STATE.RELEASING, SESSION_STATE.LOST],
  [SESSION_STATE.RELEASING]: [SESSION_STATE.RELEASED, SESSION_STATE.LOST],
  [SESSION_STATE.RELEASED]: [],
  [SESSION_STATE.FAILED]: [],
  [SESSION_STATE.LOST]: [],
} as const satisfies TransitionTable<SessionState>

export const ADMISSION_TRANSITIONS = {
  [ADMISSION_STATE.QUEUED]: [ADMISSION_STATE.RESERVED, ADMISSION_STATE.CANCELLED, ADMISSION_STATE.EXPIRED, ADMISSION_STATE.FAILED],
  [ADMISSION_STATE.RESERVED]: [ADMISSION_STATE.STARTING, ADMISSION_STATE.CANCELLED, ADMISSION_STATE.EXPIRED, ADMISSION_STATE.FAILED],
  [ADMISSION_STATE.STARTING]: [ADMISSION_STATE.ADMITTED, ADMISSION_STATE.CANCELLED, ADMISSION_STATE.EXPIRED, ADMISSION_STATE.FAILED],
  [ADMISSION_STATE.ADMITTED]: [],
  [ADMISSION_STATE.CANCELLED]: [],
  [ADMISSION_STATE.EXPIRED]: [],
  [ADMISSION_STATE.FAILED]: [],
} as const satisfies TransitionTable<AdmissionState>

export const CREATE_JOURNAL_TRANSITIONS = {
  [CREATE_JOURNAL_STATE.ACCEPTED]: [CREATE_JOURNAL_STATE.UPSTREAM_PENDING, CREATE_JOURNAL_STATE.UNCERTAIN, CREATE_JOURNAL_STATE.FAILED_TERMINAL],
  [CREATE_JOURNAL_STATE.UPSTREAM_PENDING]: [CREATE_JOURNAL_STATE.LIVE, CREATE_JOURNAL_STATE.UNCERTAIN, CREATE_JOURNAL_STATE.FAILED_TERMINAL],
  [CREATE_JOURNAL_STATE.LIVE]: [CREATE_JOURNAL_STATE.RELEASED_TERMINAL, CREATE_JOURNAL_STATE.UNCERTAIN],
  [CREATE_JOURNAL_STATE.UNCERTAIN]: [CREATE_JOURNAL_STATE.LIVE, CREATE_JOURNAL_STATE.RELEASED_TERMINAL, CREATE_JOURNAL_STATE.FAILED_TERMINAL],
  [CREATE_JOURNAL_STATE.RELEASED_TERMINAL]: [],
  [CREATE_JOURNAL_STATE.FAILED_TERMINAL]: [],
} as const satisfies TransitionTable<CreateJournalState>

export const CREATE_REPLAY_TRANSITIONS = {
  [CREATE_REPLAY_STATE.QUEUED]: [CREATE_REPLAY_STATE.RESERVED, CREATE_REPLAY_STATE.CANCELLED_TERMINAL, CREATE_REPLAY_STATE.EXPIRED_TERMINAL, CREATE_REPLAY_STATE.FAILED_TERMINAL],
  [CREATE_REPLAY_STATE.RESERVED]: [CREATE_REPLAY_STATE.STARTING, CREATE_REPLAY_STATE.CANCELLED_TERMINAL, CREATE_REPLAY_STATE.EXPIRED_TERMINAL, CREATE_REPLAY_STATE.FAILED_TERMINAL],
  [CREATE_REPLAY_STATE.STARTING]: [CREATE_REPLAY_STATE.WORKER_PENDING, CREATE_REPLAY_STATE.CANCELLED_TERMINAL, CREATE_REPLAY_STATE.EXPIRED_TERMINAL, CREATE_REPLAY_STATE.FAILED_TERMINAL],
  [CREATE_REPLAY_STATE.WORKER_PENDING]: [CREATE_REPLAY_STATE.LIVE, CREATE_REPLAY_STATE.CANCELLED_TERMINAL, CREATE_REPLAY_STATE.EXPIRED_TERMINAL, CREATE_REPLAY_STATE.FAILED_TERMINAL],
  [CREATE_REPLAY_STATE.LIVE]: [CREATE_REPLAY_STATE.RELEASED_TERMINAL],
  [CREATE_REPLAY_STATE.CANCELLED_TERMINAL]: [],
  [CREATE_REPLAY_STATE.EXPIRED_TERMINAL]: [],
  [CREATE_REPLAY_STATE.RELEASED_TERMINAL]: [],
  [CREATE_REPLAY_STATE.FAILED_TERMINAL]: [],
} as const satisfies TransitionTable<CreateReplayState>

export const MANAGER_MODE_TRANSITIONS = {
  [MANAGER_MODE.SERVING]: [MANAGER_MODE.DRAINING],
  [MANAGER_MODE.DRAINING]: [MANAGER_MODE.SERVING],
} as const satisfies TransitionTable<ManagerMode>

export const EMERGENCY_RECOVERY_TRANSITIONS = {
  [EMERGENCY_RECOVERY_STATE.MAINTENANCE]: [EMERGENCY_RECOVERY_STATE.RECOVER_MANAGER],
  [EMERGENCY_RECOVERY_STATE.RECOVER_MANAGER]: [EMERGENCY_RECOVERY_STATE.NATURAL_QUIESCENCE],
  [EMERGENCY_RECOVERY_STATE.NATURAL_QUIESCENCE]: [EMERGENCY_RECOVERY_STATE.DESTRUCTIVE_STOPPED],
  [EMERGENCY_RECOVERY_STATE.DESTRUCTIVE_STOPPED]: [EMERGENCY_RECOVERY_STATE.SAFE_FOR_LEGACY],
  [EMERGENCY_RECOVERY_STATE.SAFE_FOR_LEGACY]: [],
} as const satisfies TransitionTable<EmergencyRecoveryState>

export const LEGACY_BOOTSTRAP_TRANSITIONS = {
  [LEGACY_BOOTSTRAP_STATE.SERVING]: [LEGACY_BOOTSTRAP_STATE.EDGE_FENCED],
  [LEGACY_BOOTSTRAP_STATE.EDGE_FENCED]: [LEGACY_BOOTSTRAP_STATE.QUIESCENT],
  [LEGACY_BOOTSTRAP_STATE.QUIESCENT]: [LEGACY_BOOTSTRAP_STATE.STOPPED],
  [LEGACY_BOOTSTRAP_STATE.STOPPED]: [],
} as const satisfies TransitionTable<LegacyBootstrapState>

function canTransition<State extends string>(table: TransitionTable<State>, from: State, to: State): boolean {
  return table[from].includes(to)
}

export const canWorkerTransition = (from: WorkerState, to: WorkerState): boolean => canTransition(WORKER_TRANSITIONS, from, to)
export const canSessionTransition = (from: SessionState, to: SessionState): boolean => canTransition(SESSION_TRANSITIONS, from, to)
export const canAdmissionTransition = (from: AdmissionState, to: AdmissionState): boolean => canTransition(ADMISSION_TRANSITIONS, from, to)
export const canCreateJournalTransition = (from: CreateJournalState, to: CreateJournalState): boolean => canTransition(CREATE_JOURNAL_TRANSITIONS, from, to)
export const canCreateReplayTransition = (from: CreateReplayState, to: CreateReplayState): boolean => canTransition(CREATE_REPLAY_TRANSITIONS, from, to)
export const canManagerModeTransition = (from: ManagerMode, to: ManagerMode): boolean => canTransition(MANAGER_MODE_TRANSITIONS, from, to)
export const canEmergencyRecoveryTransition = (from: EmergencyRecoveryState, to: EmergencyRecoveryState): boolean => canTransition(EMERGENCY_RECOVERY_TRANSITIONS, from, to)
export const canLegacyBootstrapTransition = (from: LegacyBootstrapState, to: LegacyBootstrapState): boolean => canTransition(LEGACY_BOOTSTRAP_TRANSITIONS, from, to)
