export const MANAGED_PROJECT_RUNTIME_STATE = {
  ACTIVE: "ACTIVE",
  COLD_STANDBY: "COLD_STANDBY",
  STOPPED_FAILED: "STOPPED_FAILED",
} as const

export const LEGACY_RUNTIME_STATE = {
  ACTIVE: "ACTIVE",
  STOPPED_ROLLBACK: "STOPPED_ROLLBACK",
  STOPPED_FAILED: "STOPPED_FAILED",
} as const

export const DEPLOYMENT_CAPACITY_STATUS = {
  UNVERIFIED_UNTIL_TASK_41: "UNVERIFIED_UNTIL_TASK_41",
  VERIFIED: "VERIFIED",
  BLOCKED_COOLIFY_CAPACITY: "BLOCKED_COOLIFY_CAPACITY",
} as const

export const CAPACITY_GATE_OUTCOME = {
  VERIFIED: "VERIFIED",
  BLOCKED_MEMORY: "BLOCKED_MEMORY",
  BLOCKED_CPU: "BLOCKED_CPU",
  BLOCKED_DISK: "BLOCKED_DISK",
  BLOCKED_INODES: "BLOCKED_INODES",
  BLOCKED_SHM_TMPFS: "BLOCKED_SHM_TMPFS",
  BLOCKED_PRESSURE: "BLOCKED_PRESSURE",
  BLOCKED_MEASUREMENT: "BLOCKED_MEASUREMENT",
} as const

export const DEPLOYMENT_GATE_OUTCOME = {
  VERIFIED: "VERIFIED",
  BLOCKED_COOLIFY_CAPACITY: "BLOCKED_COOLIFY_CAPACITY",
  BLOCKED_SECRET_RUNTIME: "BLOCKED_SECRET_RUNTIME",
  BLOCKED_NO_SAFE_TARGET: "BLOCKED_NO_SAFE_TARGET",
  BLOCKED_COOLIFY_OPERATION: "BLOCKED_COOLIFY_OPERATION",
  BLOCKED_ROUTE_OWNERSHIP: "BLOCKED_ROUTE_OWNERSHIP",
} as const

export const CAPACITY_PHASE = {
  DISPOSABLE_CANARY: "DISPOSABLE_CANARY",
  PRODUCTION_SERIAL: "PRODUCTION_SERIAL",
} as const
export const DISK_CAPACITY_STAGE = {
  BEFORE_PULLS: "BEFORE_PULLS",
  AFTER_START: "AFTER_START",
} as const
export const INODE_CAPACITY_STAGE = {
  BEFORE_PULLS: "BEFORE_PULLS",
  AFTER_START: "AFTER_START",
} as const

export const DISCOVERY_MODE = { STATIC_CONFIG: "STATIC_CONFIG" } as const
export const COOLIFY_CUTOVER_MODE = { SERIAL_MAINTENANCE: "SERIAL_MAINTENANCE" } as const
export const COOLIFY_OPERATOR_SURFACE = {
  API: "API",
  AUTHENTICATED_SERVER_TERMINAL: "AUTHENTICATED_SERVER_TERMINAL",
} as const
export const COOLIFY_COMPOSE_DEPLOYMENT_MODE = { RAW_EXPLICIT_PROXY: "RAW_EXPLICIT_PROXY" } as const
export const COOLIFY_SECRET_ISOLATION_MODE = { RAW_COMPOSE_MANAGER_SECRET: "RAW_COMPOSE_MANAGER_SECRET" } as const
export const LEGACY_QUIESCENCE_MODE = { MAINTENANCE_NO_ORIGIN: "MAINTENANCE_NO_ORIGIN" } as const
export const EDGE_ROUTE_MODE = { COOLIFY_PROXY: "COOLIFY_PROXY", MAINTENANCE: "MAINTENANCE" } as const
export const COOLIFY_PRODUCTION_OWNER = {
  LEGACY: "LEGACY",
  MANAGED_BLUE: "MANAGED_BLUE",
  MANAGED_GREEN: "MANAGED_GREEN",
  NONE: "NONE",
} as const
export const STEEL_SERVING_TARGET = {
  LEGACY: "LEGACY",
  MANAGED_BLUE: "MANAGED_BLUE",
  MANAGED_GREEN: "MANAGED_GREEN",
  MAINTENANCE: "MAINTENANCE",
} as const
export const COMPOSITE_ROUTE_PHASE = {
  PROXY_CURRENT_OWNER: "PROXY_CURRENT_OWNER",
  MAINTENANCE_OLD_OWNER: "MAINTENANCE_OLD_OWNER",
  MAINTENANCE_NO_OWNER: "MAINTENANCE_NO_OWNER",
  MAINTENANCE_NEW_OWNER: "MAINTENANCE_NEW_OWNER",
} as const
export const FINGERPRINT_PROOF_LEVEL = {
  CONFIG_BOUND: "CONFIG_BOUND",
  RUNTIME_VERIFIED: "RUNTIME_VERIFIED",
} as const
export const COOLIFY_SCHEMA_EVIDENCE = {
  OPENAPI: "OPENAPI",
  PINNED_SOURCE_EXCEPTION: "PINNED_SOURCE_EXCEPTION",
} as const
export const SECRET_BACKUP_OPERATION = {
  READ_CANONICAL: "READ_CANONICAL",
  CREATE_CANONICAL: "CREATE_CANONICAL",
  WRITE_APP: "WRITE_APP",
  RESTORE_STOPPED_APP: "RESTORE_STOPPED_APP",
  VERIFY_FINGERPRINT: "VERIFY_FINGERPRINT",
} as const
export const COOLIFY_OPERATION_KIND = {
  READ_COOLIFY_VERSION: "READ_COOLIFY_VERSION",
  READ_OPENAPI: "READ_OPENAPI",
  READ_PROJECT: "READ_PROJECT",
  READ_ENVIRONMENT: "READ_ENVIRONMENT",
  READ_SERVER: "READ_SERVER",
  READ_DESTINATIONS: "READ_DESTINATIONS",
  DISCOVER: "DISCOVER",
  CREATE: "CREATE",
  DELETE_APPLICATION: "DELETE_APPLICATION",
  UPDATE_CONFIG: "UPDATE_CONFIG",
  READ_ENVS: "READ_ENVS",
  CREATE_ENV: "CREATE_ENV",
  UPDATE_ENV: "UPDATE_ENV",
  START: "START",
  STOP: "STOP",
  READ_DEPLOYMENT: "READ_DEPLOYMENT",
  READ_APPLICATION: "READ_APPLICATION",
  READ_PROXY_OWNER: "READ_PROXY_OWNER",
  VERIFY_STOPPED: "VERIFY_STOPPED",
} as const
export const COOLIFY_DEPLOYMENT_STATUS = {
  QUEUED: "QUEUED",
  IN_PROGRESS: "IN_PROGRESS",
  FINISHED: "FINISHED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  UNKNOWN: "UNKNOWN",
} as const
export const COOLIFY_OPERATION_STATE = {
  REQUEST_QUEUED: "REQUEST_QUEUED",
  TERMINAL_SUCCESS: "TERMINAL_SUCCESS",
  TERMINAL_FAILURE: "TERMINAL_FAILURE",
  UNKNOWN: "UNKNOWN",
} as const
export const SECRET_PROVISIONING_STATE = {
  BOTH_ABSENT: "BOTH_ABSENT",
  CANONICAL_KEY_AVAILABLE: "CANONICAL_KEY_AVAILABLE",
  WRITE_BLUE_CONFIRMED: "WRITE_BLUE_CONFIRMED",
  WRITE_GREEN_CONFIRMED: "WRITE_GREEN_CONFIRMED",
  CONFIG_RECEIPTS_MATCH: "CONFIG_RECEIPTS_MATCH",
  RUNTIME_FINGERPRINT_MATCH: "RUNTIME_FINGERPRINT_MATCH",
  PARTIAL_WRITE_RECOVERY: "PARTIAL_WRITE_RECOVERY",
  ROTATION_REQUIRED: "ROTATION_REQUIRED",
  BLOCKED_NO_CANONICAL_KEY: "BLOCKED_NO_CANONICAL_KEY",
} as const
export const MANAGED_HANDOVER_STATE = {
  ACTIVE_DRAIN_SAFE: "ACTIVE_DRAIN_SAFE",
  EDGE_MAINTENANCE: "EDGE_MAINTENANCE",
  ACTIVE_STOPPED: "ACTIVE_STOPPED",
  DOMAIN_NONE: "DOMAIN_NONE",
  STANDBY_CONFIG_BOUND: "STANDBY_CONFIG_BOUND",
  STANDBY_STARTED: "STANDBY_STARTED",
  STANDBY_RUNTIME_VERIFIED: "STANDBY_RUNTIME_VERIFIED",
  DOMAIN_STANDBY: "DOMAIN_STANDBY",
  STANDBY_SERVING: "STANDBY_SERVING",
  EDGE_COOLIFY_PROXY: "EDGE_COOLIFY_PROXY",
} as const

export type ManagedProjectRuntimeState = (typeof MANAGED_PROJECT_RUNTIME_STATE)[keyof typeof MANAGED_PROJECT_RUNTIME_STATE]
export type LegacyRuntimeState = (typeof LEGACY_RUNTIME_STATE)[keyof typeof LEGACY_RUNTIME_STATE]
export type DeploymentCapacityStatus = (typeof DEPLOYMENT_CAPACITY_STATUS)[keyof typeof DEPLOYMENT_CAPACITY_STATUS]
export type CapacityGateOutcome = (typeof CAPACITY_GATE_OUTCOME)[keyof typeof CAPACITY_GATE_OUTCOME]
export type DeploymentGateOutcome = (typeof DEPLOYMENT_GATE_OUTCOME)[keyof typeof DEPLOYMENT_GATE_OUTCOME]
export type CapacityPhase = (typeof CAPACITY_PHASE)[keyof typeof CAPACITY_PHASE]
export type DiskCapacityStage = (typeof DISK_CAPACITY_STAGE)[keyof typeof DISK_CAPACITY_STAGE]
export type InodeCapacityStage = (typeof INODE_CAPACITY_STAGE)[keyof typeof INODE_CAPACITY_STAGE]
export type DiscoveryMode = (typeof DISCOVERY_MODE)[keyof typeof DISCOVERY_MODE]
export type CoolifyCutoverMode = (typeof COOLIFY_CUTOVER_MODE)[keyof typeof COOLIFY_CUTOVER_MODE]
export type CoolifyOperatorSurface = (typeof COOLIFY_OPERATOR_SURFACE)[keyof typeof COOLIFY_OPERATOR_SURFACE]
export type CoolifyComposeDeploymentMode = (typeof COOLIFY_COMPOSE_DEPLOYMENT_MODE)[keyof typeof COOLIFY_COMPOSE_DEPLOYMENT_MODE]
export type CoolifySecretIsolationMode = (typeof COOLIFY_SECRET_ISOLATION_MODE)[keyof typeof COOLIFY_SECRET_ISOLATION_MODE]
export type LegacyQuiescenceMode = (typeof LEGACY_QUIESCENCE_MODE)[keyof typeof LEGACY_QUIESCENCE_MODE]
export type EdgeRouteMode = (typeof EDGE_ROUTE_MODE)[keyof typeof EDGE_ROUTE_MODE]
export type CoolifyProductionOwner = (typeof COOLIFY_PRODUCTION_OWNER)[keyof typeof COOLIFY_PRODUCTION_OWNER]
export type SteelServingTarget = (typeof STEEL_SERVING_TARGET)[keyof typeof STEEL_SERVING_TARGET]
export type CompositeRoutePhase = (typeof COMPOSITE_ROUTE_PHASE)[keyof typeof COMPOSITE_ROUTE_PHASE]
export type FingerprintProofLevel = (typeof FINGERPRINT_PROOF_LEVEL)[keyof typeof FINGERPRINT_PROOF_LEVEL]
export type CoolifySchemaEvidence = (typeof COOLIFY_SCHEMA_EVIDENCE)[keyof typeof COOLIFY_SCHEMA_EVIDENCE]
export type SecretBackupOperation = (typeof SECRET_BACKUP_OPERATION)[keyof typeof SECRET_BACKUP_OPERATION]
export type CoolifyOperationKind = (typeof COOLIFY_OPERATION_KIND)[keyof typeof COOLIFY_OPERATION_KIND]
export type CoolifyDeploymentStatus = (typeof COOLIFY_DEPLOYMENT_STATUS)[keyof typeof COOLIFY_DEPLOYMENT_STATUS]
export type CoolifyOperationState = (typeof COOLIFY_OPERATION_STATE)[keyof typeof COOLIFY_OPERATION_STATE]
export type SecretProvisioningState = (typeof SECRET_PROVISIONING_STATE)[keyof typeof SECRET_PROVISIONING_STATE]
export type ManagedHandoverState = (typeof MANAGED_HANDOVER_STATE)[keyof typeof MANAGED_HANDOVER_STATE]

function enumMembers(vocabulary: Readonly<Record<string, string>>): readonly string[] {
  return Object.freeze(Object.values(vocabulary))
}

export const OVERLAY_ENUM_VOCABULARY = {
  ManagedProjectRuntimeState: enumMembers(MANAGED_PROJECT_RUNTIME_STATE),
  LegacyRuntimeState: enumMembers(LEGACY_RUNTIME_STATE),
  DeploymentCapacityStatus: enumMembers(DEPLOYMENT_CAPACITY_STATUS),
  CapacityGateOutcome: enumMembers(CAPACITY_GATE_OUTCOME),
  DeploymentGateOutcome: enumMembers(DEPLOYMENT_GATE_OUTCOME),
  CoolifyCutoverMode: enumMembers(COOLIFY_CUTOVER_MODE),
  CoolifyOperatorSurface: enumMembers(COOLIFY_OPERATOR_SURFACE),
  CoolifyComposeDeploymentMode: enumMembers(COOLIFY_COMPOSE_DEPLOYMENT_MODE),
  CoolifySecretIsolationMode: enumMembers(COOLIFY_SECRET_ISOLATION_MODE),
  LegacyQuiescenceMode: enumMembers(LEGACY_QUIESCENCE_MODE),
  EdgeRouteMode: enumMembers(EDGE_ROUTE_MODE),
  CoolifyProductionOwner: enumMembers(COOLIFY_PRODUCTION_OWNER),
  SteelServingTarget: enumMembers(STEEL_SERVING_TARGET),
  CompositeRoutePhase: enumMembers(COMPOSITE_ROUTE_PHASE),
  FingerprintProofLevel: enumMembers(FINGERPRINT_PROOF_LEVEL),
  CoolifySchemaEvidence: enumMembers(COOLIFY_SCHEMA_EVIDENCE),
  SecretBackupOperation: enumMembers(SECRET_BACKUP_OPERATION),
  CoolifyOperationKind: enumMembers(COOLIFY_OPERATION_KIND),
  CoolifyDeploymentStatus: enumMembers(COOLIFY_DEPLOYMENT_STATUS),
  CoolifyOperationState: enumMembers(COOLIFY_OPERATION_STATE),
  SecretProvisioningState: enumMembers(SECRET_PROVISIONING_STATE),
  ManagedHandoverState: enumMembers(MANAGED_HANDOVER_STATE),
} as const satisfies Readonly<Record<string, readonly string[]>>

export const CAPACITY_ENUM_VOCABULARY = {
  CapacityPhase: enumMembers(CAPACITY_PHASE),
  DiskCapacityStage: enumMembers(DISK_CAPACITY_STAGE),
  InodeCapacityStage: enumMembers(INODE_CAPACITY_STAGE),
} as const satisfies Readonly<Record<string, readonly string[]>>

export const CLOSED_STATE_MEMBERS = Object.freeze(Array.from(
  new Set([
    ...Object.values(DISCOVERY_MODE),
    ...Object.values(OVERLAY_ENUM_VOCABULARY).flat(),
    ...Object.values(CAPACITY_ENUM_VOCABULARY).flat(),
  ]),
).sort())
