import { z } from "zod"

import { JsonValueSchema } from "./json-value.js"
import { ControlPlaneApiVersionSchema } from "./control-plane-contract.js"
import { UuidSchema } from "./control-plane-primitives.js"

export const MANAGED_ERROR_CODE = {
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  INVALID_CURSOR: "INVALID_CURSOR",
  ACCESS_AUTH_REQUIRED: "ACCESS_AUTH_REQUIRED",
  ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  ADMISSION_NOT_FOUND: "ADMISSION_NOT_FOUND",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_ACCEPTABLE: "NOT_ACCEPTABLE",
  MANAGED_SESSION_REQUIRED: "MANAGED_SESSION_REQUIRED",
  SESSION_STATE_CONFLICT: "SESSION_STATE_CONFLICT",
  CREATE_TOKEN_CONFLICT: "CREATE_TOKEN_CONFLICT",
  EVENT_CURSOR_RESTARTED: "EVENT_CURSOR_RESTARTED",
  LIST_CURSOR_RESTARTED: "LIST_CURSOR_RESTARTED",
  INSTANCE_LOST: "INSTANCE_LOST",
  EVENT_CURSOR_EXPIRED: "EVENT_CURSOR_EXPIRED",
  LIST_CURSOR_EXPIRED: "LIST_CURSOR_EXPIRED",
  BODY_TOO_LARGE: "BODY_TOO_LARGE",
  RESULT_TOO_LARGE: "RESULT_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  MANAGED_FEATURE_UNSUPPORTED: "MANAGED_FEATURE_UNSUPPORTED",
  TOOL_INPUT_INVALID: "TOOL_INPUT_INVALID",
  ADMISSION_TIMEOUT: "ADMISSION_TIMEOUT",
  QUEUE_FULL: "QUEUE_FULL",
  RATE_LIMITED: "RATE_LIMITED",
  UPSTREAM_BAD_RESPONSE: "UPSTREAM_BAD_RESPONSE",
  NO_REACHABLE_WORKER: "NO_REACHABLE_WORKER",
  MANAGER_DRAINING: "MANAGER_DRAINING",
  MANAGED_LIMITER_CAPACITY: "MANAGED_LIMITER_CAPACITY",
  MANAGED_TICKET_CAPACITY: "MANAGED_TICKET_CAPACITY",
  MANAGED_IDEMPOTENCY_CAPACITY: "MANAGED_IDEMPOTENCY_CAPACITY",
  MANAGED_SNAPSHOT_CAPACITY: "MANAGED_SNAPSHOT_CAPACITY",
  MANAGED_INGRESS_CAPACITY: "MANAGED_INGRESS_CAPACITY",
  MANAGED_AI_RESULT_CAPACITY: "MANAGED_AI_RESULT_CAPACITY",
  MANAGED_ACTION_CAPACITY: "MANAGED_ACTION_CAPACITY",
  MANAGED_WS_CAPACITY: "MANAGED_WS_CAPACITY",
  WORKER_JOURNAL_CAPACITY: "WORKER_JOURNAL_CAPACITY",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
  TOOL_TIMEOUT: "TOOL_TIMEOUT",
} as const
export type ManagedErrorCode = (typeof MANAGED_ERROR_CODE)[keyof typeof MANAGED_ERROR_CODE]

type ErrorCatalogRow = Readonly<{ readonly status: number; readonly retryable: boolean }>
const row = (status: number, retryable = false): ErrorCatalogRow => ({ status, retryable })

export const MANAGED_ERROR_CATALOG = {
  [MANAGED_ERROR_CODE.INVALID_ARGUMENT]: row(400),
  [MANAGED_ERROR_CODE.INVALID_CURSOR]: row(400),
  [MANAGED_ERROR_CODE.ACCESS_AUTH_REQUIRED]: row(401),
  [MANAGED_ERROR_CODE.ACCESS_FORBIDDEN]: row(403),
  [MANAGED_ERROR_CODE.SESSION_NOT_FOUND]: row(404),
  [MANAGED_ERROR_CODE.ADMISSION_NOT_FOUND]: row(404),
  [MANAGED_ERROR_CODE.RESULT_NOT_FOUND]: row(404),
  [MANAGED_ERROR_CODE.TOOL_NOT_FOUND]: row(404),
  [MANAGED_ERROR_CODE.ROUTE_NOT_FOUND]: row(404),
  [MANAGED_ERROR_CODE.METHOD_NOT_ALLOWED]: row(405),
  [MANAGED_ERROR_CODE.NOT_ACCEPTABLE]: row(406),
  [MANAGED_ERROR_CODE.MANAGED_SESSION_REQUIRED]: row(409),
  [MANAGED_ERROR_CODE.SESSION_STATE_CONFLICT]: row(409),
  [MANAGED_ERROR_CODE.CREATE_TOKEN_CONFLICT]: row(409),
  [MANAGED_ERROR_CODE.EVENT_CURSOR_RESTARTED]: row(409),
  [MANAGED_ERROR_CODE.LIST_CURSOR_RESTARTED]: row(409),
  [MANAGED_ERROR_CODE.INSTANCE_LOST]: row(410),
  [MANAGED_ERROR_CODE.EVENT_CURSOR_EXPIRED]: row(410),
  [MANAGED_ERROR_CODE.LIST_CURSOR_EXPIRED]: row(410),
  [MANAGED_ERROR_CODE.BODY_TOO_LARGE]: row(413),
  [MANAGED_ERROR_CODE.RESULT_TOO_LARGE]: row(413),
  [MANAGED_ERROR_CODE.UNSUPPORTED_MEDIA_TYPE]: row(415),
  [MANAGED_ERROR_CODE.MANAGED_FEATURE_UNSUPPORTED]: row(422),
  [MANAGED_ERROR_CODE.TOOL_INPUT_INVALID]: row(422),
  [MANAGED_ERROR_CODE.ADMISSION_TIMEOUT]: row(429, true),
  [MANAGED_ERROR_CODE.QUEUE_FULL]: row(429, true),
  [MANAGED_ERROR_CODE.RATE_LIMITED]: row(429, true),
  [MANAGED_ERROR_CODE.UPSTREAM_BAD_RESPONSE]: row(502),
  [MANAGED_ERROR_CODE.NO_REACHABLE_WORKER]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGER_DRAINING]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_LIMITER_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_TICKET_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_IDEMPOTENCY_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_SNAPSHOT_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_INGRESS_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_AI_RESULT_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_ACTION_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.MANAGED_WS_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.WORKER_JOURNAL_CAPACITY]: row(503, true),
  [MANAGED_ERROR_CODE.UPSTREAM_TIMEOUT]: row(504, true),
  [MANAGED_ERROR_CODE.TOOL_TIMEOUT]: row(504, true),
} as const satisfies Readonly<Record<ManagedErrorCode, ErrorCatalogRow>>

export const ManagedErrorCodeSchema = z.nativeEnum(MANAGED_ERROR_CODE)
export const ManagedErrorEnvelopeSchema = z.object({
  apiVersion: ControlPlaneApiVersionSchema,
  error: z.object({
    code: ManagedErrorCodeSchema,
    message: z.string().min(1).max(1_024),
    retryable: z.boolean(),
    requestId: UuidSchema,
    details: JsonValueSchema.optional(),
  }).strict(),
}).strict().superRefine((envelope, context) => {
  if (MANAGED_ERROR_CATALOG[envelope.error.code].retryable !== envelope.error.retryable) {
    context.addIssue({ code: z.ZodIssueCode.custom, message: "error retryability differs from catalog" })
  }
})
