export const FINGERPRINT_RECEIPT_KIND = {
  CONFIG_WRITE: "CONFIG_WRITE_RECEIPT",
  STARTED_MANAGER: "STARTED_MANAGER_RECEIPT",
} as const

export const RECEIPT_SIGNATURE_ALGORITHM = {
  HMAC_SHA256: "HMAC_SHA256",
} as const

export const MANAGED_SECRET_ENVIRONMENT_KEY = "STEEL_MANAGED_CREATE_TOKEN_KEY_HEX"

export const FINGERPRINT_RECEIPT_ERROR_CODE = {
  KEY_ID_MISMATCH: "KEY_ID_MISMATCH",
  FINGERPRINT_MISMATCH: "FINGERPRINT_MISMATCH",
} as const
