export const MANAGER_INIT_VERIFICATION_SURFACE = {
  SYNTHETIC_CONTRACT: "SYNTHETIC_CONTRACT",
  LIVE_LINUX: "LIVE_LINUX",
} as const

export const MANAGER_INIT_PLATFORM = {
  CONTRACT_FIXTURE: "CONTRACT_FIXTURE",
  LINUX: "LINUX",
} as const

export const MANAGER_INIT_MOUNT_EVIDENCE_SOURCE = {
  SYNTHETIC_EXPECTED_CONTRACT: "SYNTHETIC_EXPECTED_CONTRACT",
  PROC_SELF_MOUNTINFO: "PROC_SELF_MOUNTINFO",
} as const

export const MANAGER_INIT_DESTINATION_MOUNT = {
  PATH: "/run/steel",
  FILE_SYSTEM_TYPE: "tmpfs",
  SOURCE: "tmpfs",
  UID: 10_001,
  GID: 10_001,
  MODE: 0o700,
  SIZE_BYTES: 8_388_608,
} as const

export const MANAGER_INIT_MOUNT_FLAG = {
  READ_WRITE: "rw",
  NO_SETUID: "nosuid",
  NO_DEVICES: "nodev",
  NO_EXECUTE: "noexec",
} as const

export const REQUIRED_MANAGER_INIT_MOUNT_FLAGS = [
  MANAGER_INIT_MOUNT_FLAG.READ_WRITE,
  MANAGER_INIT_MOUNT_FLAG.NO_SETUID,
  MANAGER_INIT_MOUNT_FLAG.NO_DEVICES,
  MANAGER_INIT_MOUNT_FLAG.NO_EXECUTE,
] as const

export const MANAGER_INIT_EXECUTION_RECEIPT_KIND = {
  SYNTHETIC_CONTRACT: "SYNTHETIC_CONTRACT_EXECUTION",
} as const

export const MANAGER_INIT_CLEANUP_STATUS = {
  NOT_APPLICABLE: "NOT_APPLICABLE",
} as const

export const MANAGER_INIT_VERIFICATION_RESULT_KIND = {
  CONFIG_BOUND: "CONFIG_BOUND",
  LIVE_PROOF_DEFERRED_TO_TASK_41: "LIVE_PROOF_DEFERRED_TO_TASK_41",
} as const

export const MANAGER_INIT_FD_TARGET_CLASS = {
  STDIN: "STDIN",
  STDOUT: "STDOUT",
  STDERR: "STDERR",
} as const

export const MANAGER_INIT_DESCRIPTOR_KIND = {
  SOURCE: "SOURCE",
  DESTINATION: "DESTINATION",
} as const

export const MANAGER_INIT_OPEN_FLAG = {
  O_RDONLY: "O_RDONLY",
  O_WRONLY: "O_WRONLY",
  O_CREAT: "O_CREAT",
  O_EXCL: "O_EXCL",
  O_CLOEXEC: "O_CLOEXEC",
  O_NOFOLLOW: "O_NOFOLLOW",
} as const

export const MANAGER_LINUX_CAPABILITY = {
  CHOWN: "CHOWN",
  SETUID: "SETUID",
  SETGID: "SETGID",
  SETPCAP: "SETPCAP",
} as const

export const MANAGER_STATUS_CAP_FIELD = {
  INHERITABLE: "CapInh",
  PERMITTED: "CapPrm",
  EFFECTIVE: "CapEff",
  BOUNDING: "CapBnd",
  AMBIENT: "CapAmb",
} as const

export const REQUIRED_MANAGER_STATUS_CAP_FIELDS = [
  MANAGER_STATUS_CAP_FIELD.INHERITABLE,
  MANAGER_STATUS_CAP_FIELD.PERMITTED,
  MANAGER_STATUS_CAP_FIELD.EFFECTIVE,
  MANAGER_STATUS_CAP_FIELD.BOUNDING,
  MANAGER_STATUS_CAP_FIELD.AMBIENT,
] as const

export const MANAGER_INIT_STEP = {
  OPEN_SOURCE: "OPEN_SOURCE",
  VALIDATE_SOURCE: "VALIDATE_SOURCE",
  OPEN_DESTINATION: "OPEN_DESTINATION",
  COPY_VALIDATE: "COPY_VALIDATE",
  FSYNC_DESTINATION: "FSYNC_DESTINATION",
  CLOSE_SECRET_DESCRIPTORS: "CLOSE_SECRET_DESCRIPTORS",
  ZEROIZE_PLAINTEXT: "ZEROIZE_PLAINTEXT",
  SCAN_FDS_BEFORE_DROP: "SCAN_FDS_BEFORE_DROP",
  SETGROUPS_EMPTY: "SETGROUPS_EMPTY",
  DROP_CAPABILITY_BOUNDING_SET: "DROP_CAPABILITY_BOUNDING_SET",
  SET_NO_NEW_PRIVS: "SET_NO_NEW_PRIVS",
  SETRESGID: "SETRESGID",
  SETRESUID: "SETRESUID",
  CLEAR_CAPABILITY_SETS: "CLEAR_CAPABILITY_SETS",
  VERIFY_STATUS: "VERIFY_STATUS",
  SCAN_FDS_AFTER_DROP: "SCAN_FDS_AFTER_DROP",
  EXEC_MANAGER: "EXEC_MANAGER",
} as const

export const MANAGER_INIT_SEQUENCE = [
  MANAGER_INIT_STEP.OPEN_SOURCE,
  MANAGER_INIT_STEP.VALIDATE_SOURCE,
  MANAGER_INIT_STEP.OPEN_DESTINATION,
  MANAGER_INIT_STEP.COPY_VALIDATE,
  MANAGER_INIT_STEP.FSYNC_DESTINATION,
  MANAGER_INIT_STEP.CLOSE_SECRET_DESCRIPTORS,
  MANAGER_INIT_STEP.ZEROIZE_PLAINTEXT,
  MANAGER_INIT_STEP.SCAN_FDS_BEFORE_DROP,
  MANAGER_INIT_STEP.SETGROUPS_EMPTY,
  MANAGER_INIT_STEP.DROP_CAPABILITY_BOUNDING_SET,
  MANAGER_INIT_STEP.SET_NO_NEW_PRIVS,
  MANAGER_INIT_STEP.SETRESGID,
  MANAGER_INIT_STEP.SETRESUID,
  MANAGER_INIT_STEP.CLEAR_CAPABILITY_SETS,
  MANAGER_INIT_STEP.VERIFY_STATUS,
  MANAGER_INIT_STEP.SCAN_FDS_AFTER_DROP,
  MANAGER_INIT_STEP.EXEC_MANAGER,
] as const

export const MANAGER_INIT_ERROR_CODE = {
  LIVE_PROOF_DEFERRED_TO_TASK_41:
    MANAGER_INIT_VERIFICATION_RESULT_KIND.LIVE_PROOF_DEFERRED_TO_TASK_41,
} as const
