export const PRODUCTION_DEPENDENCY_AUDIT = {
  SCHEMA_VERSION: 1,
  KIND: "STEEL_PRODUCTION_DEPENDENCY_AUDIT",
  NODE_IMAGE: "docker.io/library/node:22.23.1-bookworm@sha256:5647be709086c696ff32edaaf1c70cd26d1da6ab2b39c32f3c7b4c4a31957e37",
  NODE_VERSION: "22.23.1",
  REGISTRY_ORIGIN: "https://registry.npmjs.org",
  RESIDUAL_REASON: "UNINSTALLED_LOCKFILE_ONLY",
  MAX_RESIDUALS: 32,
  MAX_RESIDUAL_ADVISORY_SOURCES: 64,
  MAX_RESIDUAL_NODES: 256,
} as const

export const PRODUCTION_DEPENDENCY_AUDIT_TARGET = {
  WORKER: "WORKER",
  MANAGER: "MANAGER",
} as const

export const PRODUCTION_DEPENDENCY_PACKAGE_KIND = {
  WORKSPACE: "WORKSPACE",
  REGISTRY: "REGISTRY",
} as const

export const PRODUCTION_DEPENDENCY_AUDIT_SEVERITY = {
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const

export const PRODUCTION_DEPENDENCY_AUDIT_PLATFORM = {
  OS: "linux",
  ARCHITECTURE: "amd64",
} as const
