export const PROTOCOL_KIND = {
  REST: "REST",
  WEBSOCKET: "WEBSOCKET",
} as const

export const HTTP_METHOD = {
  ALL: "ALL",
  DELETE: "DELETE",
  GET: "GET",
  HEAD: "HEAD",
  OPTIONS: "OPTIONS",
  POST: "POST",
} as const

export const AFFINITY_RULE = {
  CREATE: "CREATE",
  NONE: "NONE",
  PATH_SESSION_ID: "PATH_SESSION_ID",
  UNSCOPED_ACTIVE_SESSION: "UNSCOPED_ACTIVE_SESSION",
} as const

export const LIFECYCLE_CLASS = {
  ACTION: "ACTION",
  CONTEXT: "CONTEXT",
  CREATE: "CREATE",
  DEBUG: "DEBUG",
  DOCUMENTATION: "DOCUMENTATION",
  EVENT: "EVENT",
  FILE: "FILE",
  HEALTH: "HEALTH",
  LIVE_DETAILS: "LIVE_DETAILS",
  LOG: "LOG",
  READ: "READ",
  RELEASE: "RELEASE",
  SELENIUM: "SELENIUM",
  WEBSOCKET: "WEBSOCKET",
} as const

export const SESSION_ID_MODE = {
  CLIENT_SUPPLIED: "CLIENT_SUPPLIED",
  UPSTREAM_RETURNED: "UPSTREAM_RETURNED",
} as const

export const CREATE_JOURNAL_BINDING = {
  CLIENT_ID_DIRECT: "CLIENT_ID_DIRECT",
  CREATE_TOKEN_TO_UPSTREAM_RETURNED_ID: "CREATE_TOKEN_TO_UPSTREAM_RETURNED_ID",
} as const

export const WEBSOCKET_UPGRADE_CLASS = {
  CAST: "CAST",
  LOGS: "LOGS",
  PAGE_ID: "PAGE_ID",
  RECORDING: "RECORDING",
  ROOT_CDP: "ROOT_CDP",
} as const

export const WEBSOCKET_MESSAGE_KIND = {
  BROWSER_GET_VERSION: "BROWSER_GET_VERSION",
  OPEN_NO_MESSAGE: "OPEN_NO_MESSAGE",
  TAB_LIST: "TAB_LIST",
} as const

export const WEBSOCKET_MESSAGE_BY_UPGRADE = {
  [WEBSOCKET_UPGRADE_CLASS.CAST]: WEBSOCKET_MESSAGE_KIND.TAB_LIST,
  [WEBSOCKET_UPGRADE_CLASS.LOGS]: WEBSOCKET_MESSAGE_KIND.OPEN_NO_MESSAGE,
  [WEBSOCKET_UPGRADE_CLASS.PAGE_ID]: WEBSOCKET_MESSAGE_KIND.OPEN_NO_MESSAGE,
  [WEBSOCKET_UPGRADE_CLASS.RECORDING]: WEBSOCKET_MESSAGE_KIND.OPEN_NO_MESSAGE,
  [WEBSOCKET_UPGRADE_CLASS.ROOT_CDP]: WEBSOCKET_MESSAGE_KIND.BROWSER_GET_VERSION,
} as const

export const RUNTIME_CONDITION = {
  ALWAYS: "ALWAYS",
  LOG_STORAGE_ENABLED: "LOG_STORAGE_ENABLED",
} as const

export const BODY_KIND = {
  BINARY: "BINARY",
  EMPTY: "EMPTY",
  HTML: "HTML",
  JSON: "JSON",
  MULTIPART: "MULTIPART",
  SSE: "SSE",
  TEXT: "TEXT",
  YAML: "YAML",
} as const
