export const WORKER_DOCKERFILE_OVERLAY = {
  AUDIT_BOUNDARIES: [
    "node managed/security/generate-native-overlay-evidence.mjs",
    "node managed/security/prune-production-tree.mjs --target WORKER --root /runtime-deps",
    "npm audit --registry=https://registry.npmjs.org",
    "node managed/security/verify-production-audit.mjs",
    "--builder-root /workspace",
    "--installed-root /runtime-deps",
    "--source-revision \"${MANAGED_SOURCE_REVISION}\"",
    "--source-tree-sha256 \"${MANAGED_SOURCE_TREE_SHA256}\"",
    'dev.happycastle.steel.production-audit.sha256="${MANAGED_PRODUCTION_AUDIT_RECEIPT_SHA256}"',
    "sha256sum /app/managed/production-dependency-audit.json",
  ],
  RUNTIME: [
    "COPY --from=runtime-dependencies /runtime-deps/node_modules /app/node_modules",
    "COPY --from=build /workspace/api/build /app/api/build",
    "COPY --from=runtime-dependencies /runtime-deps/api/node_modules /app/api/node_modules",
    "COPY --from=build /workspace/api/extensions/recorder/dist /app/api/extensions/recorder/dist",
    "COPY --from=build /workspace/api/extensions/recorder/icon.png /app/api/extensions/recorder/icon.png",
    "COPY --from=build /workspace/api/extensions/recorder/manifest.json /app/api/extensions/recorder/manifest.json",
    "COPY --from=build /workspace/api/extensions/recorder/package-lock.json /app/api/extensions/recorder/package-lock.json",
    "COPY --from=build /workspace/api/extensions/recorder/package.json /app/api/extensions/recorder/package.json",
    "COPY --from=build /workspace/ui/dist /app/ui/dist",
    "COPY --from=build /workspace/managed/shared/build /app/managed/shared/build",
    "COPY --from=build /workspace/managed/worker/build /app/managed/worker/build",
    "COPY --from=build /workspace/package.json /app/package.json",
    "COPY --from=build /workspace/package-lock.json /app/package-lock.json",
    "COPY --from=build /workspace/api/package.json /app/api/package.json",
    "COPY --from=build /workspace/ui/package.json /app/ui/package.json",
    "COPY --from=build /workspace/managed/shared/package.json /app/managed/shared/package.json",
    "COPY --from=build /workspace/managed/worker/package.json /app/managed/worker/package.json",
    "COPY --from=build /workspace/runtime-source-manifest.json /app/managed/runtime-source-manifest.json",
    "COPY --from=production-audit-input /production-dependency-audit.json /app/managed/production-dependency-audit.json",
  ],
} as const
